// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"encoding/json"
	"net"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Device struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	MacAddress net.HardwareAddr
	IpAddress  pqtype.Inet
	Connected  bool
	UserID     uuid.UUID
}

type Directory struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
	ParentID    uuid.NullUUID
	UserID      uuid.UUID
}

type Note struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Content     json.RawMessage
	DirectoryID uuid.UUID
	UserID      uuid.UUID
}

type User struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	FirstName     string
	LastName      string
	Bio           sql.NullString
	EmailAddress  string
	EmailVerified bool
	Hash          []byte
}
