// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"
	"net"

	"github.com/google/uuid"
)

type Querier interface {
	FindDeviceByID(ctx context.Context, id uuid.UUID) (Device, error)
	FindDeviceByMAC(ctx context.Context, macAddress net.HardwareAddr) (Device, error)
	FindDevicesByUser(ctx context.Context, userID uuid.UUID) ([]Device, error)
	FindUserByEmail(ctx context.Context, emailAddress string) (User, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UserExistsByEmail(ctx context.Context, emailAddress string) (int64, error)
}

var _ Querier = (*Queries)(nil)
